import type { Note, Person, Practice, TopicId } from "@/content/site";

export const site = {
  name: "Halden",
  legalName: "Halden",
  email: "atelier@halden.cz",
  description:
    "Halden is a law firm in Prague and Vienna. We act for owners, management and families in decisions where the wording matters as much as the result.",
  founded: "2009",
  lawyers: "28",
};

export const nav = [
  { to: "/en/practices", label: "Practices" },
  { to: "/en/approach", label: "Approach" },
  { to: "/en/studio", label: "Studio" },
  { to: "/en/people", label: "People" },
  { to: "/en/notes", label: "Notes" },
];

export const practices: Practice[] = [
  {
    slug: "transakce",
    index: "01",
    title: "Transactions and corporate",
    summary: "A sale, an investor’s entry, and a contract that survives the first dispute.",
    lead: "We lead share sales, investor entries and changes to constitutional documents. The partner who takes the matter is at the table until closing.",
    when: [
      "You are selling a majority stake and the buyer already has counsel.",
      "An investor is coming in and the current owner is staying.",
      "The articles were written in peacetime and you are now arguing about them.",
    ],
    work: [
      "The structure of the deal before the data room opens.",
      "Contracts in which risk is named, not scattered through schedules.",
      "Negotiations attended by someone entitled to say no.",
      "A closing without a night-time surprise in the warranties.",
    ],
    decline: "We do not take auctions whose only brief is to push down the cost of the legal work.",
    people: ["klara-holan"],
  },
  {
    slug: "spory",
    index: "02",
    title: "Disputes and arbitration",
    summary: "Court, arbitration, or a settlement that ends sooner than the proceedings.",
    lead: "We take disputes in which a sentence has already been said that cannot be taken back. First we say whether a claim should be filed at all.",
    when: [
      "The other side refuses to talk and the limitation period is shortening.",
      "You sit on a board and the company wants to carry you as the one at fault.",
      "The arbitration clause is in a contract you did not sign.",
    ],
    work: [
      "A view on whether a claim improves the position, or only spends time.",
      "A written strategy on one page, not ten.",
      "Representation in court and arbitration in the Czech Republic and Austria.",
      "A settlement that can be performed, not merely announced.",
    ],
    decline: "We do not run disputes for the principle unless the client says so out loud, and in advance.",
    people: ["marek-voss"],
  },
  {
    slug: "majetek",
    index: "03",
    title: "Wealth and succession",
    summary: "A handover that does not break the firm or the relationships.",
    lead: "We arrange ownership so that it outlives the people who hold it today. Usually in Czech and German, often across the border.",
    when: [
      "The second generation is meant to enter and no one wants to open the first sentence.",
      "The wealth sits in the company, in a Vienna property, and in one person’s head.",
      "You want a trust structure that someone who did not draft it can still understand in ten years.",
    ],
    work: [
      "A map of the assets, without euphemism.",
      "A succession order that separates ownership from management.",
      "Trust and company structures in the Czech Republic and Austria.",
      "A document the family can bear to read aloud.",
    ],
    decline: "We do not build structures whose only purpose is to hide from someone in the family.",
    people: ["elena-susicka"],
  },
  {
    slug: "regulace",
    index: "04",
    title: "Regulation and supervision",
    summary: "The answer should be in a document, not in one person’s memory.",
    lead: "We prepare regulated firms for the question that has not arrived yet. AML, financial supervision, internal rules that someone actually keeps.",
    when: [
      "An inspection is coming and the “governance” folder is a folder in name only.",
      "A licence, a notification, or a change of the controlling person.",
      "An internal rule exists, but it does not match how the firm actually works.",
    ],
    work: [
      "The gap between the rule and the practice, written without alibi.",
      "Answers to the supervisor that stay with the question.",
      "AML and internal governance documents the business can live with.",
      "Preparing directors for an oral hearing.",
    ],
    decline: "We do not write policies meant to hang on a wall and never be opened.",
    people: ["tomas-lind"],
  },
  {
    slug: "nemovitosti",
    index: "05",
    title: "Real estate",
    summary: "The risk is usually in the definition of area, not in the opening clause.",
    lead: "Acquisitions, development and leases. We read the schedules. We act for developers, owners and tenants who build or hold for the long term.",
    when: [
      "You are buying a site and the seller is in a hurry to sign.",
      "One key tenant’s lease carries the whole model.",
      "A planning decision, an easement or a neighbour weighs more than the price.",
    ],
    work: [
      "Title review, and the contracts that hang on the title.",
      "Building contracts and leases with definitions that can be measured.",
      "Talks with the financing bank, without two parallel truths.",
      "A calm closing of the land, not only of the building.",
    ],
    decline: "We do not lead speculative purchases where the client does not want to know the defect before signing.",
    people: ["adam-riha"],
  },
  {
    slug: "prace-vedeni",
    index: "06",
    title: "Work of directors",
    summary: "A director’s contract, an exit, and liability. Discreet, and in time.",
    lead: "We hold the line between the company’s interest and the interest of the person who leads it. Before that line is looked for in court.",
    when: [
      "You are joining a board and the contract arrived as “standard”.",
      "You are leaving, and competition, severance and confidentiality are in one sentence.",
      "The firm wants you to carry a liability you have no means to direct.",
    ],
    work: [
      "Service contracts and management agreements.",
      "Exits, releases and non-competes that will hold.",
      "Separating advice to the company from advice to the person.",
      "Silence where silence belongs, and paper where there is no protection without it.",
    ],
    decline: "We do not act for a company and its director in the same matter.",
    people: ["nils-berg"],
  },
];

export const people: Person[] = [
  {
    slug: "klara-holan",
    name: "Klára Holan",
    given: "KH",
    role: "Managing partner",
    focus: "Transactions and corporate",
    city: "Prague",
    languages: "Czech, English",
    bio: [
      "She leads the firm and the transactions in which one voice has to hold from the first call to closing.",
      "Before Halden she was in-house counsel to an industrial group. Hence the dislike of advice that cannot be signed.",
    ],
    matters: ["transakce"],
  },
  {
    slug: "marek-voss",
    name: "Marek Voss",
    given: "MV",
    role: "Partner",
    focus: "Disputes and arbitration",
    city: "Prague",
    languages: "Czech, English",
    bio: [
      "He leads disputes and the negotiations meant to replace them. He writes short. In a meeting he speaks even less.",
      "Clients call him when a sentence has already been said that cannot be taken back, and what remains is to decide what to do with it.",
    ],
    matters: ["spory"],
  },
  {
    slug: "elena-susicka",
    name: "Elena Sušická",
    given: "ES",
    role: "Partner",
    focus: "Wealth and succession",
    city: "Vienna",
    languages: "Czech, German, English",
    bio: [
      "She arranges ownership so that it outlives the people who hold it today.",
      "She works with families who have a firm on both sides of the border, and she insists the document can be read aloud.",
    ],
    matters: ["majetek"],
  },
  {
    slug: "tomas-lind",
    name: "Tomáš Lind",
    given: "TL",
    role: "Partner",
    focus: "Regulation and supervision",
    city: "Prague",
    languages: "Czech, English",
    bio: [
      "He prepares regulated firms for the question that has not arrived yet.",
      "He sees to it that the answer is in a document, not in the memory of one person who has just gone on leave.",
    ],
    matters: ["regulace"],
  },
  {
    slug: "adam-riha",
    name: "Adam Říha",
    given: "AŘ",
    role: "Counsel",
    focus: "Real estate",
    city: "Prague",
    languages: "Czech, English",
    bio: [
      "He reads the schedules. Development, acquisitions and leases in which the risk hides in the definition of area, not in the opening clause.",
      "He goes to the site before the contract is opened. The paper and the land have to describe the same thing.",
    ],
    matters: ["nemovitosti"],
  },
  {
    slug: "nils-berg",
    name: "Nils Berg",
    given: "NB",
    role: "Counsel",
    focus: "Work of directors",
    city: "Vienna",
    languages: "German, Czech, English",
    bio: [
      "Directors’ contracts, exits and liability.",
      "He holds the line between the company’s interest and the interest of the person who leads it, and he says so when that line cannot be held in the same matter.",
    ],
    matters: ["prace-vedeni"],
  },
];

export const notes: Note[] = [
  {
    slug: "ticho-ve-smlouve",
    title: "Silence in a contract",
    date: "2026-03-12",
    displayDate: "12 March 2026",
    minutes: 6,
    excerpt: "A missing sentence looks like elegance for three years. Then it becomes a reading no one wanted.",
    sections: [
      {
        heading: "What a missing sentence does in three years",
        paragraphs: [
          "A short contract is not automatically a good one. It is short when every sentence that is not in it is missing on purpose. Most contracts we read after a dispute are short by accident. The parties understood each other on the day they signed. They understood each other in the room. A room cannot be summoned three years later.",
          "Silence in a contract is worth something only where the law fills the gap in a way both sides can bear. When the gap is filled by industry habit, one manager’s memory, or whoever has the stronger lawyer that day, the silence was not elegant. It was lazy.",
        ],
      },
      {
        heading: "Definitions, not the preamble",
        paragraphs: [
          "An opening statement about partnership and trust will not decide a dispute. What decides it is the definition of area, EBITDA, control, or the phrase “material adverse change”, which no one can apply to an actual number.",
          "When a client asks for a shorter contract, we do not cut the definitions. We cut the adjectives. A good definition is shorter than a paragraph of reassurance, and you can lean on it without both sides having to go back to an email from May.",
        ],
      },
      {
        heading: "When silence belongs",
        paragraphs: [
          "Silence belongs to what the statute already says clearly, and to what you do not want to make worse by accident in the contract. It belongs to trade secrets that do not belong in the contract at all. It does not belong to the price, to who bears a defect, or to how the matter ends when you stop understanding each other.",
          "Before we send a contract, we ask one thing: which sentence would be looked for in three years by someone who was not at the signing. If the answer is not in the contract, we either write it in, or we write to the client why we have left it out on purpose.",
        ],
      },
    ],
  },
  {
    slug: "due-diligence-bez-archivu",
    title: "Due diligence without an archive",
    date: "2026-01-20",
    displayDate: "20 January 2026",
    minutes: 7,
    excerpt: "A review should not end as a folder. It should end as a page on which a decision can be made.",
    sections: [
      {
        heading: "What to read first",
        paragraphs: [
          "A data room can pretend to be complete. Four hundred files are not the same as knowledge. We read first what carries the money and what carries the liability: ownership, the key contracts, disputes, debt, and the people without whom the firm is not the firm.",
          "The rest we order by what would change the price, or the decision not to go on. Not by the alphabet of folders the seller prepared.",
        ],
      },
      {
        heading: "What to leave",
        paragraphs: [
          "We leave the history that no longer has an owner. An old trade name, a contract ended years ago, a policy no one uses. We write that we left it, and why. Silence in a review is the same as silence in a contract: either it is on purpose, or it is a hole.",
          "We do not chase formal completeness where the client is buying a specific risk and knows it. A review is not a collection of marks. It is a filter.",
        ],
      },
      {
        heading: "One page for the person who decides",
        paragraphs: [
          "The output is not a report that only its author can carry. The output is a page: what holds, what is a condition of signing, what is a price reduction, what is a reason to walk away. The schedules, for the person who will live with the matter day to day, come after that.",
          "If the page does not fit on a page, we do not yet understand the matter well enough to send it on.",
        ],
      },
    ],
  },
  {
    slug: "kdy-nepodavat",
    title: "When not to file a claim",
    date: "2025-11-04",
    displayDate: "4 November 2025",
    minutes: 5,
    excerpt: "A claim is a tool. It is not proof that you are right, and it is not a substitute for a sentence you did not say in time.",
    sections: [
      {
        heading: "A cost that is not in the tariff",
        paragraphs: [
          "A court costs money that can be counted, and attention that cannot. A management that lives a dispute for two years is not leading the firm. That is not a reason not to bring the dispute. It is a reason to know that you are bringing it.",
          "Before we recommend filing, we write what happens if you lose, and what happens if you win and the other side does not pay. A judgment is not a payment.",
        ],
      },
      {
        heading: "When the other side wants the same thing",
        paragraphs: [
          "Some disputes are about a sentence both sides want, they just do not want to say it first. There a claim is a way to lose a month. An agreement that names the defect and the remedy is often shorter than a prayer for relief, and it can be performed on a Tuesday.",
          "We negotiate when the negotiation has a mandate. A meeting with no power to say no is theatre. We tell the client that before we accept it.",
        ],
      },
      {
        heading: "A written exit",
        paragraphs: [
          "Sometimes the right thing is not to file, and to leave. Then it has to be on paper: why we are not going to court, what the client is accepting, and until when the decision can be taken back. Without that, a year later “we did not file” becomes “we forgot”.",
          "Halden would rather write a short no than a long claim meant to cover the fact that there is no brief.",
        ],
      },
    ],
  },
];

export const steps = [
  { index: "01", title: "Listening", text: "One partner. No hand-off chain. First we find out whether we are the right firm for the matter." },
  { index: "02", title: "Frame", text: "We write what is certain, what is a choice, and what is a risk. Scope and a fee cap are part of the frame, not an appendix." },
  { index: "03", title: "Work", text: "A small team. A written sequence. No surprise in the hours, and no report that only its author can carry." },
  { index: "04", title: "After signing", text: "We stay until the matter lives on its own. Then we leave. We do not bill for presence." },
];

export const principles = [
  { title: "One voice", text: "The partner who accepts the matter leads it. An associate writes. The partner answers for the sentence that goes out." },
  { title: "Written scope", text: "Before we begin, it is on paper what we do and what we do not. A change of scope is a new decision, not a quiet growth of the invoice." },
  { title: "A cap", text: "The fee is an agreed scope. An hourly rate only where the scope cannot be closed — and even then with a cap you know in advance." },
  { title: "Refusal", text: "Matters that do not fit us we do not dress up. We say so within two working days, as quickly as a yes." },
];

export const clients = [
  "Owners of industrial groups in Central Europe",
  "Families before handing on the firm",
  "Regulated firms ahead of an inspection",
  "Directors who need their own voice, not the company’s",
];

export const facts = [
  { value: "2009", lines: ["Studio in Prague", "Founded"] as const },
  { value: "2018", lines: ["A desk in Vienna", "Not a second name"] as const },
  { value: "28", lines: ["Lawyers", "One standard"] as const },
  { value: "1", lines: ["A partner on it", "Through to the end"] as const },
];

export const questions = [
  { q: "Who does Halden work for?", a: "Owners, management and families. Companies, when the brief is precise. We do not run the ordinary file that needs a large network and shift work." },
  { q: "How quickly do you reply?", a: "Within two working days. If we do not take the matter, we say so just as quickly and, if we can, where to turn." },
  { q: "How do you charge?", a: "An agreed scope and a cap. By the hour only where the scope cannot be closed in advance, and even then with a limit you know before we start." },
  { q: "In which languages do you run a matter?", a: "Czech, English and German. We write the contract in the language the parties will actually read, not the one that sounds better in a presentation." },
  { q: "Do you take one question, not a whole dispute?", a: "Yes, if the question is precise and can be answered in writing. No, if you are looking for a general survey of the law, or a second opinion without the papers." },
  { q: "Do you publish clients’ names?", a: "No. A reference is arranged by the partner who led the matter, and only with the client’s consent. We do not carry logos on the site." },
];

export const cities = [
  { name: "Prague", text: "A meeting after it is confirmed. The first conversation can be in writing, if the matter is sensitive or the client is not in the city." },
  { name: "Vienna", text: "The same standard of writing, not a branch with a different hand. A meeting after it is confirmed, mostly for matters across the border." },
];

export const ui = {
  skip: "Skip to content",
  office: "Law firm",
  citiesLine: "Prague · Vienna",
  contact: "Contact",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  theme: "Switch colour mode",
  toEnglish: "English",
  toCzech: "Česky",
  navMain: "Main",
  navMobile: "Mobile",
  navFooter: "Footer",
  homeAria: "Halden, home",
  footerBlurb: "A law firm for decisions that carry weight. Prague and Vienna, one standard of writing.",
  privacy: "Privacy",
  cookies: "Cookies",
  cookieSettings: "Cookie settings",
  meetPrague: "Prague — a meeting once confirmed",
  meetVienna: "Vienna — a meeting once confirmed",
  disclaimer: "Nothing on this site is legal advice, and it does not create a lawyer–client relationship.",
  creditBefore: "A concept for sale",
  creditAfter: "made by studiovoid.cz",
  cookieBar:
    "Essential storage keeps only your choice and the colour mode in this browser. Measurement is a local page counter — we send nothing on.",
  cookieMore: "More about cookies",
  cookieSettingsBtn: "Settings",
  cookieEssentialOnly: "Essential only",
  cookieAllow: "Allow measurement",
  cookieTitle: "Cookies",
  cookieDialog: "The choice is stored only in this browser. You can change it at any time.",
  cookieNecessary: "Essential",
  cookieNecessaryText: "Stores consent and the colour mode. Always on.",
  cookieOn: "On",
  cookieMeasure: "Measurement",
  cookieMeasureText: "A counter of page views in this browser. No outside tool, nothing sent to a server.",
  cookieViews: "{n} views so far.",
  notFoundTitle: "This page is not here.",
  notFoundText: "The address does not match. Go back to the start, or write if you are looking for something specific.",
  notFoundHome: "Home",
  crumbs: "Breadcrumb",
  heroTitle: "Calm in decisions that carry weight.",
  heroLede: "We act for owners, management and families. Few matters at once. Each one to the end.",
  heroCta: "Arrange a consultation",
  heroMore: "Our philosophy",
  heroAlt: "The Halden team.",
  quote: "Halden is not a network. It is a firm in which the partner who takes a matter also leads it.",
  quoteText:
    "Clients come when they no longer want another presentation. They want a formulation they can stand on, and a person who answers for it after signing.",
  quoteLink: "About the studio",
  practicesKicker: "Six practices",
  kickerPractices: "Practices",
  kickerApproach: "Approach",
  kickerStudio: "Studio",
  kickerPeople: "People",
  all: "All",
  clientsTitle: "Who we work with",
  clientsText: "We do not publish clients’ names. A reference is arranged by the partner who led the matter, and only with their consent.",
  endQuote: "The work ends when the matter lives without us.",
  endText: "We do not bill for presence. We stay while we are needed, and then we leave.",
  endLink: "The approach to each matter",
  peopleKicker: "People who will lead the matter",
  everyone: "Everyone",
  notesKicker: "Notes",
  closing: "Write when you want to speak with a partner.",
  practicesTitle: "Six things we know how to lead.",
  practicesLede: "None of them is a side line, and we do not keep one just so the site looks complete. If a matter does not fit, we say so.",
  metaPractices: "Six practices at Halden: transactions, disputes, wealth, regulation, real estate and the work of directors.",
  when: "When to come",
  work: "What we do",
  leads: "Leads",
  writeAbout: "Write about this matter",
  areaNav: "Further practices",
  areaPrev: "Previous",
  areaNext: "Next",
  metaPracticeFallback: "A practice of the firm Halden.",
  peopleTitle: "Who will lead the matter is clear before we begin.",
  peopleLede: "Four partners and two counsel. No anonymous teams, and no hand-off after the first meeting.",
  metaPeople: "Partners and counsel at Halden. One matter has one person who leads it.",
  area: "Practice",
  writeTo: "Write to",
  metaPersonFallback: "People at Halden.",
  approachTitle: "First the frame. Then the work. Then we leave.",
  approachLede: "A client should know who leads, what is in scope, and when we stop. That is not a process chart. It is the condition on which we take a matter.",
  metaApproach: "How Halden leads a matter: one partner, a written scope, a fee cap, and a leaving when we are no longer needed.",
  paperAlt: "A stack of thick cotton paper and a steel ruler on a dark table.",
  paperCaption: "One page on which a decision can be made.",
  principlesTitle: "Four rules that cannot be walked around with an appendix.",
  questionsTitle: "Questions we are asked before the file",
  write: "Write",
  studioTitle: "A firm, not a network.",
  studioLede: "Halden began in Prague in 2009. Vienna was added in 2018 as a desk, not as a second name. The writing is the same on both sides of the border.",
  metaStudio: "Halden began in Prague in 2009. Since 2018 it has had a desk in Vienna. One firm, one standard of writing.",
  corridorAlt: "A long empty corridor of pale oak and blue-grey plaster, daylight at the end.",
  facadeAlt: "A night facade of limestone with one narrow window and warm light inside.",
  facadeCaption: "Prague and Vienna. A meeting only after it is confirmed.",
  whyName: "Why the name",
  studioP1: "Studio, because a matter has an author. Not because we are any less strict about the statute. {n} lawyers hold one standard: a short text, a named risk, a partner who will sign the sentence.",
  studioP2: "We do not run branches that borrow a logo. When a matter goes past what we can do, we say so and we recommend someone who can do it better. That is part of the calm, not a gap in the offer.",
  studioP3: "We are not on the league tables of the front page. Trust is in who leads the matter and how it is written. A reference is arranged by the partner, not by marketing.",
  where: "Where we meet",
  peopleBoth: "People in both cities",
  notesTitle: "We write only when there is something to say.",
  notesLede: "No newsletter, and no retelling of a statute. Texts from matters that repeat.",
  metaNotes: "Short texts from Halden on contracts, review, and when not to file a claim.",
  min: "min",
  minRead: "min read",
  noteDisclaimer: "This text is not legal advice. If you are dealing with something similar,",
  noteWrite: "write to a partner",
  metaNoteFallback: "A note from Halden.",
  contactTitle: "The first message can be short.",
  contactLede: "We reply within two working days. If we do not take the matter, we say so just as quickly. We do not publish a telephone number — the first contact is in writing.",
  metaContact: "Write to Halden. We reply within two working days. The first contact is in writing.",
  sent: "Thank you. The message is ready. In this presentation it is not stored and not sent — in practice it would go to the partner who would lead the matter.",
  name: "Name",
  email: "Email",
  topic: "What the matter is about",
  choose: "Choose",
  message: "Message",
  consentBefore: "I want to continue. In this presentation the message is not stored and not sent. More in the",
  consentLink: "privacy notice",
  sendError: "The message could not be prepared. Try again, or write to",
  sending: "Sending",
  send: "Send",
  direct: "Directly",
  errName: "Please write your name.",
  errNameLong: "The name is too long.",
  errEmail: "Enter a valid email.",
  errEmailLong: "The email is too long.",
  errTopic: "Choose what the matter is about.",
  errMessage: "Write at least a few sentences, so we know what to talk about.",
  errMessageLong: "The message is too long.",
  errConsent: "Without consent we will not take the message.",
  cookiesTitle: "Two choices. Both do what they say.",
  cookiesLede: "We do not use third-party advertising or analytics. The difference between the choices is only whether the browser remembers how many pages were viewed.",
  metaCookies: "What the Halden site stores in the browser, and how to change the choice. No third-party cookies.",
  necessaryTitle: "Essential",
  necessaryBody: "The key halden-consent remembers whether you have already chosen. The key halden-theme remembers light or dark. Without them the bar would ask on every visit and the mode would return to dark. These stay in the browser.",
  measureTitle: "Measurement",
  measureOn: "Measurement is on, and this browser has {n} views.",
  measureOff: "Measurement is not running.",
  measureBody: "If you allow measurement, the key halden-views increases a number on the first visit to a page in the session. We send the number nowhere. If you refuse measurement, we delete the key.",
  changeTitle: "How to change the choice",
  changeBody: "Open settings. The same window is in the footer of every page. You can also clear the browser by hand.",
  openSettings: "Open settings",
  privacyKicker: "Privacy",
  privacyTitle: "Data we do not want from you without a reason.",
  privacyLede: "This page describes the Halden site as a presentation. It is not legal advice, and it does not replace what a controller would give in live operation.",
  metaPrivacy: "How Halden treats personal data in this presentation. The form is not stored and not sent.",
  whoTitle: "Who runs the site",
  whoBefore: "The presentation is led under the name",
  whoAfter: "Contact:",
  whoNote: "We do not give a registration number or a registered office, because this is a designed site, not a public extract of a specific firm.",
  formTitle: "What happens to a message from the form",
  formBody: "The form on the Contact page checks the shape of the data on the server and stores nothing. Name, email and the text of the message are not written to a database, not sent by email, and do not appear in the application log. After the server replies they remain only in your browser’s memory until you leave the page.",
  browserTitle: "What the browser stores",
  browserBody: "Colour mode and the cookie choice live in this browser’s localStorage. If you allow measurement, a local counter of pages viewed is added. That counter does not leave the device. If you choose essential only, we delete the counter. The detail is on the page",
  choicesTitle: "Your choices",
  choicesBody: "You can change the cookie choice at any time from Cookie settings in the footer. You can also delete the local data by clearing this site’s storage in the browser. For anything further, write to",
  privacyDate: "In force on 24 September 2026.",
  topics: [
    { id: "transakce" as TopicId, label: "Transactions and corporate" },
    { id: "spory" as TopicId, label: "Disputes and arbitration" },
    { id: "majetek" as TopicId, label: "Wealth and succession" },
    { id: "regulace" as TopicId, label: "Regulation and supervision" },
    { id: "nemovitosti" as TopicId, label: "Real estate" },
    { id: "prace-vedeni" as TopicId, label: "Work of directors" },
    { id: "nevim" as TopicId, label: "I don’t yet know where it belongs" },
  ],
};
